### ISSUE TITLE
"Fullscreen" issue

### ISSUE THREAD

**Issue by endeffects** [syncfusion/ej2-aspnet-core-blazor-samples#27]
I tried to display the diagram with 100% height and width.
I also set up all parent contains like html and body to 100% heigth and width.
Due the fact that the diagram itself has the position:relativ style it does not render.
When i remove the relativ positioning in the chrome dev tools the diagram is shown.
Is there any option to fix this behavior?

![image](https://user-images.githubusercontent.com/13432569/59625604-05073580-913a-11e9-9856-626f65a0d83a.png)

**Comment by RamyaThiru** [comment]
Hi @endeffects,

We suspect that the height is not set as 100 percentage for diagram and any of its parent div element. This may be the root cause for diagram rendering issue. 
Please set the diagram model width and height as 100 percentage and for its all parent div size as 100 percentage to resolve the issue. We have provided the simple sample to represent this. Please refer to the sample as below.

Sample: http://www.syncfusion.com/downloads/support/directtrac/general/ze/DiagramParentSizeSample1747682242

Could you please provide us the modified sample and video to replicate the issue if this issue is still exists after validating the provided sample? This will help us to provide you the appropriate solution at the earliest.

Regards,
Ramya T

**Comment by endeffects** [comment]
Thank you alot, you example helped me to fix the issue.
Great support :)
