### ISSUE TITLE
Palette does not support getNodeDefaults

### ISSUE THREAD

**Issue by endeffects** [syncfusion/ej2-aspnet-core-blazor-samples#30]
I'm trying to create new nodes from palette, but all i get is a clone of the existing node in the palette. So i was looking into your docu and for other frameworks this is done by using getNodeDefaults and getConnectorDefaults. But this seems not to be fully supported in the current version. 

Also i got an issue that when i try to add such a clone to my diagram that it does not deselect itself after dropping it. I'm not able to do anything in this state. The console shows the following error: 

> treemap.ts:2 Error: <rect> attribute width: A negative value is not valid. ("-1.7976931348623157e+308")

![image](https://user-images.githubusercontent.com/13432569/59976588-f18b1d00-95c6-11e9-8c7f-429170f5029a.png)

![image](https://user-images.githubusercontent.com/13432569/59966741-e087d080-9520-11e9-89ea-28c087d6847a.png)

Btw: The node is an inherited DiagramNode Instance.

**Comment by RamyaThiru** [comment]
Hi @endeffects,
Queries | Response
-- | --
So i was   looking into your docu and for other frameworks this is done by using   getNodeDefaults and getConnectorDefaults. But this seems not to be fully   supported in the current version. | Currently   we don’t have getNodeDefaults and getConnectorDefaults support in Blazor. We   have logged this as a feature request and it will be available in our Volume   3 release on October 2019. We will get back to you once our Volume 3 release   is rolled out.       We have   created simple sample to achieve drag and drop elements from palette to   Diagram. Please refer to the sample as below.           Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/SymbolPaletteSample-2027363582
it does not deselect   itself after dropping it. I'm not able to do anything in this state. The   console shows the following error:   treemap.ts:2 Error:   attribute width: A negative value is not valid.   ("-1.7976931348623157e+308") | We were   unable to replicate an issue  with the dropped objects. Could you check   the provided sample ? Please provide us the video or modified sample if this   issue still exists.

**Comment by endeffects** [comment]
Thanks for your help, i have uploaded a sample here:
https://1drv.ms/u/s!AvfU-VGBgXuLg-o1FobpHy9VVnqADg?e=QxFQEv

Please drag and drop multiple elements from palette to force the issue.

**Comment by RamyaThiru** [comment]
Hi @endeffects ,

Thanks for sharing the sample to represent the issue.

The reported issue occurs due to a node and connector id starts with number. For an SVG element, an id should start with a letter, non-ASCII letters. Please refer to below link.   
Link: https://oreillymedia.github.io/Using_SVG/guide/markup.html  
 
We have modified the sample based on the above guideline to resolve the issue. Please refer to the modified sample as below.

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/240032/ze/Syncfusion-DragDrop-527797951


Sample changes: We have changed id of the node and connector in BasedNode.razor.cs and Connector.cs files.

Feature information:

Requirement : getNodeDefaults and getConnectorDefaults support in Blazor.

This requirement can be tracked through the below feedback link. This feature will be available in our Volume 3 release on October 2019.

Link: https://www.syncfusion.com/feedback/7116/provide-method-call-back-support-in-blazor

We will get back to you once our Volume 3 release is rolled out.  

Regards,
Ramya T

**Comment by endeffects** [comment]
Thanks alot for your help, this was new to me.
