### ISSUE TITLE
Fullscreen FitToPage issue 

### ISSUE THREAD

**Issue by endeffects** [syncfusion/ej2-aspnet-core-blazor-samples#32]
I'm running a diagram in fullscreen mode (100% heigth and width), also I've initilized some nodes on application start. The browser window itself is not fullscreen. So when i run the application the view port of the diagram is larger than the browser window and the scroll bars are set on the bottom right. It looks like that the viewport uses the dimensions of the screen and not of the current browser. When i maximize the browser window to fullscreen everthing is correct and the scrollbars are gone, same when i "minimize" the browser window to the previous dimensions. So the diagram seems not to be initilized correctly on application start.

**Comment by RamyaThiru** [comment]
Hi @endeffects ,

We suspect that the height is not set as 100 percentage for diagram and any of its parent div element. This may be the root cause for full screen fit to page issue. 
Please set the diagram model width and height as 100 percentage and for its all parent div size as 100 percentage to resolve the issue. We have provided the simple sample to represent this. Please refer to the sample as below.

Sample: http://www.syncfusion.com/downloads/support/directtrac/general/ze/DiagramParentSizeSample1747682242

Could you please provide us the modified sample and video to replicate the issue if this issue still exists after validating the provided sample? This will help us to provide you the appropriate solution at the earliest.

Regards,
Ramya T

**Comment by endeffects** [comment]
Thanks for your reply, i have uploaded a sample here to demonstrate this issue:
https://1drv.ms/u/s!AvfU-VGBgXuLg-o1FobpHy9VVnqADg?e=QxFQEv

**Comment by RamyaThiru** [comment]
Hi @endeffects,

Thanks for sharing the sample to represent the issue.

The padding property of scrollSettings is assigned with specific margin which extends the scrollable region based on the scroll limit. This is root cause of reported issue with scrollbar. Please remove the padding property from your sample to resolve the reported issue. Please refer to the modified sample as below.

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/240034/ze/Syncfusion-DragDrop_and_scrollbar1627606887

Sample changes: In Diagram.cs file, we have removed the padding property of scrollSettings. 

Regards, 
Ramya T

**Comment by endeffects** [comment]
Thank you, i thought i tried this before.
