### ISSUE TITLE
DiagramConstraints throws IndexOutOfBoundException

### ISSUE THREAD

**Issue by endeffects** [syncfusion/ej2-aspnet-core-blazor-samples#33]
Sample:

`<ej-diagram id="diagram" width="900px" height="600px" constraints="DiagramConstraints.Default | DiagramConstraints.Bridging" bridge-direction="Bottom"></ej-diagram>`

**Comment by RamyaThiru** [comment]
Hi ,

Reported issue: Diagram throws IndexOutOfBoundException 

We can reproduce the reported issue when using Bridging Constraint in Diagram. We will fix the issue and include it in our Volume 2 main release on July 2019.  We will get back to you once our Volume 2 main release is rolled out.

Regards,
Ramya T

**Comment by endeffects** [comment]
Thank you.

**Comment by RamyaThiru** [comment]
Hi @endeffects,

Reported issue: Diagram throws IndexOutOfBoundException

The reported issue can be tracked through the below feedback link.

https://www.syncfusion.com/feedback/7115/diagram-throws-index-out-of-bounds-exception-when-using-bridging-constraint

We will get back to you once our Volume 2 main release is rolled out. 

Regards,
Ramya T

**Comment by endeffects** [comment]
I get the same error for the DiagramTools:

`<Diagram id="diagram" @ref="Diagram" Nodes="@Nodes" Connectors="@Connectors" Width="100%" Height="100%" Tool="DiagramTools.Default | DiagramTools.ZoomPan" />`

**Comment by RamyaThiru** [comment]
Hi @endeffects ,

Query | Response
-- | --
I found one more problem   here, I get the same error for the DiagramTools:   <Diagram id="diagram"   @ref="Diagram" Nodes="@Nodes"   Connectors="@Connectors" Width="100%"   Height="100%" Tool="DiagramTools.Default \|   DiagramTools.ZoomPan" /> | We can reproduce the   issue with Tool property and this issue is similar to constraints issue. We   have updated the definition of the defect based on this. Please refer to the   updated feedback link.        Link: https://www.syncfusion.com/feedback/7115/diagram-throws-index-out-of-bound-exception-when-using-constraints-and-tools       The fix will be   available in our Volume 2 main release on July 2019. We will get back to you   once our Volume 2 main release is rolled out.
Btw: Is the ZoomPan   similar to the one on your charts? A real control with plus and minus?   I'm looking for something like this: | We have support to   perform zoom In/Out operations in diagram by using ZoomOptions parameter and   ZoomTo method. But there is no control is available in diagram for zoom   in/out like chart.       We have created a   simple sample with buttons to achieve zoom operations. Please refer to the   sample as below.           Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/zoomsample-843174762

Regards,
Ramya T

**Comment by endeffects** [comment]
Thanks alot for your help. The zooming works as expected.

**Comment by RamyaThiru** [comment]
Hi,

Reported issue: Diagram throws IndexOutOfBoundException 

We are glad to announce that our weekly package is released successfully. We have included the fix for the reported issue with this weekly release . Please upgrade to your latest version(17.2.0.34-beta ).

Link: https://www.nuget.org/packages/Syncfusion.EJ2.Blazor/17.2.0.34-beta

Regards,
Ramya T
